### add order for  user
POST http://localhost:3030/orders
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhbnRlZC5kci5hbGlAZ21haWwuY29tIiwic3ViIjoxLCJyb2xlIjoidXNlciIsImlhdCI6MTc2ODk5ODM1NCwiZXhwIjoxNzY4OTk5MjU0fQ.vfEzOi2xwP4_h7sO4-jSRMHDz9d0dVjUJCCl-nuAxvQ

{
  "productId": 4
}

//--------------------------------------------test for admin ---------------------------------//
### find all orders (admin)
GET http://localhost:3030/orders?page=1&limit=40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4OTk4MzgxLCJleHAiOjE3Njg5OTkyODF9.b5S6LGppJqMiDCXGxeDoC2lX4OhHuq6XtbjRSV4grlU


### approve order (admin)
POST http://localhost:3030/orders/32/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4OTk4MzgxLCJleHAiOjE3Njg5OTkyODF9.b5S6LGppJqMiDCXGxeDoC2lX4OhHuq6XtbjRSV4grlU

### reject order (admin)
POST http://localhost:3030/orders/4/reject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4OTAxNzIxLCJleHAiOjE3Njg5MDI2MjF9.JmBOezA9TchC7EtDoypDptyyjhLyLhZqlhoGFz3jXCM
