### add order for  user
POST http://localhost:3030/orders
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndhbnRlZC5kci5hbGlAZ21haWwuY29tIiwic3ViIjoxLCJyb2xlIjoidXNlciIsImlhdCI6MTc2OTY4NjIzMCwiZXhwIjoxNzY5Njg3MTMwfQ.OIxYRE-_3eDMUAkJoZtRwjlr4BasGOzZlyKV9obtfRo

{
  "productId": 4
}

//--------------------------------------------test for admin ---------------------------------//
### find all orders (admin)
GET http://localhost:3030/orders?page=1&limit=40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY5Njg2Mjc4LCJleHAiOjE3Njk2ODcxNzh9.pT3jNAMsDMKVx_9RXSuI7sI8Wm5cxS8_TYW8azm0SAg


### approve order (admin)
POST http://localhost:3030/orders/38/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY5Njg2Mjc4LCJleHAiOjE3Njk2ODcxNzh9.pT3jNAMsDMKVx_9RXSuI7sI8Wm5cxS8_TYW8azm0SAg

### reject order (admin)
POST http://localhost:3030/orders/4/reject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4OTAxNzIxLCJleHAiOjE3Njg5MDI2MjF9.JmBOezA9TchC7EtDoypDptyyjhLyLhZqlhoGFz3jXCM
