### register user
POST http://localhost:3030/auth/register
Content-Type: application/json

{
  "email": "knolkm@gmail.com",
  "password": "123456",
  "firstName": "othman",
  "lastName": "othman",
  "phoneNumber": "0785894865"
}

### signin email: admin , pass: admin1 
POST http://localhost:3030/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin1"
}

